# Generated by Django 4.2.11 on 2026-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
