# Generated by Django 4.2.11 on 2026-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Select payment method'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('card', 'Card'), ('online_payment', 'Online Payment'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
