# Generated by Django 4.2.11 on 2026-08-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method_order_payment_method_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(blank=True, max_length=150)),
                ('method', models.CharField(blank=True, choices=[('', 'Select payment method'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('card', 'Card'), ('online_payment', 'Online Payment'), ('other', 'Other')], default='', max_length=30)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
