# Generated by Django 4.2.11 on 2026-08-12 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
