# Generated by Django 4.2.11 on 2026-08-13 05:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_details_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('present_days', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='orders.employee')),
            ],
            options={
                'ordering': ['-pay_period_end', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=20)),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='orders.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
