# Generated by Django 4.2.11 on 2026-08-17 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_employee_payroll_employeeattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='e.g. Post-lunch, Overtime', max_length=100)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='orders.employeeattendance')),
            ],
            options={
                'ordering': ['check_in'],
            },
        ),
    ]
